language: android
jdk:
  - oraclejdk8
notifications:
  slack:
    secure: J0guzv7EVIElf9CdWpOpUZDmetmsh2J0jyFoSfULfi5EFJffapPGFPe8wNXOpsJG8Oz/kzUXgtZ29obIE0yzRI17Zs24laoemQvzteHATIc6qeBjjAwN3amMwa3Q0Afgls4LzwSJmyzUGot6qGtxYjz2i0+Zl8J5xdivKqHhTZHAZQP0H/y5OUovZABk3PZyOk7d0pRiharimhLmqU0p+Ji5ilY032fFVwa7JBHaVwSG7/JsQcuQL4Jh4lcLYjv7EIjBZlosSxbEXuZxPgRMhTakJrVgRFjsOTuC3UwZDVZFG5ofWZPmm8snOJIhb2XKhzf9PPmC89yyGh2Q889RS3NqJjFW5V8Lx5LHFqzooTrFu4gxiPDc+UVwlXwvAW6KduNhoIbbncwELlHDPJvh20ugopxqemS4rHuQpLpvuwF+WcV068FmAtSgp06mVw36Q+AkCYCN2dxgDErOjGnnI75taeslaE0Zg+OmD3V8U9rZm13kuiAfYDbbkbtmdlcLxD+Gkph9SDzkyQdMwaLVm4cTZHmDk5YsuAe7+/jQgrI5jnTaDPN1YATjOPO5/bFlJ81JkZX4BMNYWdc6KW8pqtV++msWvfkfVWc+kOwZuGeK0jukXU+yxVF5ZET42XObOirIn8sLLqFkNPwAmPDEN7TqpbRyrmpVhTgnklmdS6k=
